version: '3.7'

services:
  postgres_container:
    container_name: postgres_container
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secrect
    networks:
      - backend
    ports:
      - 5433:5432
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8001:8001'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres_container
    depends_on:
      - postgres_container

networks:
  backend:
    driver: bridge
